### ISSUE TITLE
Reverse FHIR to CDA transformation

### ISSUE THREAD

**Issue by josemolmomillan** [srdc/cda2fhir#5]
Hello,
   in a prototype i am developing I need to transform my fhir resources to CDA docs in order to interoperate with a old system which just supports this interoperability standard.

   do you guys think we could use this project to develop the other fhir2cda conversion?

Regards

**Comment by msfyuksel** [comment]
Hi,

You cannot use the code directly as only one way transformation is implemented in this project. However, the implemented mapping information between FHIR resources and CDA structures might assist you. Please note though that FHIR DSTU2 resources are used in this project. 

Best,
