### ISSUE TITLE
Quick install question

### ISSUE THREAD

**Issue by jxfish2** [srdc/cda2fhir#9]
I am relatively new to Maven, and I am not 100% certain of the answer here:

In your documentation, you state to run the following commands:

mvn install

mvn clean install

Do I need to run both commands, or just one of them?

I am assuming if it is just one, that "mvn install" would be acceptable for the very first installation attempt.

I am assuming if this is a secondary, or repeat install, that I would want to run the "mvn clean install".

Am I correct in my assumption?

If yes, can you tweak the wording to indicate one or the other?

Thanks in advance.

**Comment by msfyuksel** [comment]
Hi,

Your interpretation is correct!

Best,
Mustafa
